services:
  server:
    build: .
    image: builded-server-image
    env_file: .env # Используем конкретный файл с перменными окружения
    networks:
     - network1
    volumes:
      - server_data:/artifacts/data # Используем не путь, а хранилище докера для volumes
    
  app:
    image: python:3.12-slim # Используем конкретный путь
    networks:
      - network2

volumes:
  server_data:

networks:
  network1:
  network2:

