FROM python:3.12-slim
# Использование более сжатого образа
# Указан конкретный тег, что обеспечивает стабильность

WORKDIR /app
# Установка рабочего каталога

COPY requirements.txt .

RUN pip install -r requirements.txt
# Сначала копируем только файл с зависимостями и устанавливаем их

COPY . .

CMD ["python3", "main.py"]

